name = "RNASeqTools"
uuid = "c929925e-1c85-4562-9573-d68085edd19a"
authors = ["Malte Siemers <malte.siemers@uni-jena.de>"]
version = "0.2.0"

[deps]
BGZFStreams = "28d598bf-9b8f-59f1-b38c-5a06b4a0f5e6"
BigWig = "9d649c22-cb6b-11e8-1fa9-f3896fced444"
BioAlignments = "00701ae9-d1dc-5365-b64a-a3a3ebf5695e"
BioGenerics = "47718e42-2ac5-11e9-14af-e5595289c2ea"
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
GFF3 = "af1dc308-cb6b-11e8-32f0-31192efa90f6"
GenomicFeatures = "899a7d2d-5c61-547b-bef9-6698a8d05446"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
MultipleTesting = "f8716d33-7c4a-5097-896f-ce0ecbd3ef6b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
XAM = "d759349c-bcba-11e9-07c2-5b90f8f05f7c"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
